ci: Use macos-11 in all CI (#5493)
### Description
Addresses two issues:
1. The nightly builds are starting to occasionally fail because the
`macos-latest` runners are struggling to complete integration test
shards in under 2 hours. It seems likely the newer ARM-based runners are
underpowered.
2. ~`macos-11` runners will be removed by 6/28, and will start
temporarily failing on 6/17. Better to move off them now.~ `macos-12`
hits a compiler error on DAST.cs for some reason (`error CS8078: An
expression is too long or complex to compile`) so we'll stick to
`macos-11` for this PR

### How has this been tested?
`run-deep-tests` label

<small>By submitting this pull request, I confirm that my contribution
is made under the terms of the [MIT
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>