Services refactoring (#4278)
### Changes

- All calls to `IServiceProvider.GetRequiredService<T>()` are now done
at startup, which prevents `ObjectDisposedException` and
`ContainerException` when tests are winding down, which would create
noise in our logs

Example of a noisy log line:
```
fail: Microsoft.Dafny.LanguageServer.Workspace.TelemetryPublisher[0]
      exception occurred
      DryIoc.ContainerException: code: Error.ContainerIsDisposed;
      message: Container is disposed and should not be used: "container without scope has been DISPOSED!
       You may include Dispose stack-trace into the message via:
      container.With(rules => rules.WithCaptureContainerDisposeStackTrace())"
         at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3)
         at DryIoc.Container.ThrowIfContainerDisposed()
         at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
         at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.Dafny.LanguageServer.Workspace.CompilationAfterTranslation..ctor(IServiceProvider services, CompilationAfterResolution compilationAfterResolution, IReadOnlyDictionary`2 diagnostics, IReadOnlyList`1 verificationTasks, List`1 counterexamples, Dictionary`2 implementationIdToView, VerificationTree verificationTree) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer/Workspace/Documents/CompilationAfterTranslation.cs:line 34
         at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.PrepareVerificationTasksAsync(CompilationAfterResolution loaded, CancellationToken cancellationToken) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer/Workspace/CompilationManager.cs:line 163
         at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.TranslateAsync() in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer/Workspace/CompilationManager.cs:line 117
```
Taken from
https://github.com/dafny-lang/dafny/actions/runs/5541261307/jobs/10114441465?pr=3902

- `IFilesystem` has been removed as a field for classes where it wasn't
needed
- `VerificationProgressReporter` is now a service instead of an instance
that was created for every compilation, which matches better with its
name

### Testing
Since this a refactoring, no additional testing is needed.

<small>By submitting this pull request, I confirm that my contribution
is made under the terms of the [MIT
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>